<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Setup 2FA - SecuRx</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="antialiased bg-slate-50 text-gray-800 min-h-screen flex items-center justify-center relative selection:bg-securx-cyan selection:text-white py-12">

    <div class="absolute top-[5%] left-[10%] w-96 h-96 bg-securx-cyan/20 rounded-full blur-[100px] pointer-events-none fixed"></div>
    <div class="absolute bottom-[5%] right-[10%] w-[400px] h-[400px] bg-securx-navy/15 rounded-full blur-[120px] pointer-events-none fixed"></div>

    <div class="glass-panel p-8 md:p-12 z-10 mx-4 w-full max-w-4xl relative">
        
        <div class="flex flex-col items-center mb-10 text-center border-b border-gray-200/60 pb-8">
            <div class="w-16 h-16 bg-securx-cyan/10 rounded-full flex items-center justify-center text-securx-cyan mb-4 border border-securx-cyan/20">
                <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
            </div>
            <h1 class="text-3xl font-extrabold text-securx-navy mb-2">Secure Your Account</h1>
            <p class="text-gray-500 font-medium text-sm max-w-xl">
                Two-factor authentication adds an extra layer of security to your medical profile. Once enabled, you will be prompted to enter a secure 6-digit code from your phone when logging in.
            </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
            
            <div class="space-y-6">
                <h3 class="text-lg font-bold text-securx-navy flex items-center gap-2">
                    <span class="bg-securx-cyan text-white w-6 h-6 rounded-full flex items-center justify-center text-xs">1</span>
                    Scan QR Code
                </h3>
                <p class="text-sm text-gray-600">Open your authenticator app (like Google Authenticator or Authy) and scan this QR code.</p>
                
                <div class="bg-white p-4 rounded-xl border border-gray-200 shadow-sm inline-block mx-auto">
                    <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=SecuRx:ProviderApp" alt="2FA QR Code" class="w-40 h-40">
                </div>

                <div class="pt-4 border-t border-gray-100">
                    <h3 class="text-lg font-bold text-securx-navy flex items-center gap-2 mb-2">
                        <span class="bg-securx-cyan text-white w-6 h-6 rounded-full flex items-center justify-center text-xs">2</span>
                        Enter the Code
                    </h3>
                    <p class="text-sm text-gray-600 mb-3">Type the 6-digit code generated by your app to verify setup.</p>
                    <form action="#" method="POST" class="flex gap-3">
                        <input type="text" placeholder="000000" class="glass-input w-full py-2.5 px-4 text-center tracking-widest text-lg font-bold" maxlength="6">
                        <button type="button" class="glass-btn-primary px-6">Verify</button>
                    </form>
                </div>
            </div>

            <div class="bg-securx-navy/5 border border-securx-navy/10 rounded-xl p-6 h-full flex flex-col">
                <h3 class="text-lg font-bold text-securx-navy mb-3 flex items-center gap-2">
                    <svg class="w-5 h-5 text-securx-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                    Recovery Codes
                </h3>
                <p class="text-sm text-gray-600 mb-4 leading-relaxed">
                    Store these recovery codes in a secure password manager. They can be used to recover access to your account if your two-factor authentication device is lost.
                </p>
                
                <div class="bg-white/60 border border-white/80 rounded-lg p-4 font-mono text-sm text-securx-navy grid grid-cols-2 gap-3 mb-6 shadow-inner">
                    <div>1a2b-3c4d</div>
                    <div>5e6f-7g8h</div>
                    <div>9i0j-1k2l</div>
                    <div>3m4n-5o6p</div>
                    <div>7q8r-9s0t</div>
                    <div>1u2v-3w4x</div>
                </div>

                <div class="mt-auto">
                    <button type="button" class="w-full glass-btn-secondary py-2.5 text-sm">
                        Download Codes (.txt)
                    </button>
                </div>
            </div>

        </div>
    </div>
</body>
</html>