@extends('layouts.patient')

@section('page_title', 'Clinical Record')

@section('content')
    <div class="max-w-6xl mx-auto space-y-6">

        <div
            class="p-6 bg-slate-800 border border-slate-700 rounded-2xl shadow-xl flex items-center gap-5 text-slate-200 relative overflow-hidden">
            <div class="absolute top-0 right-0 w-64 h-64 bg-securx-cyan/5 rounded-bl-full pointer-events-none"></div>

            <div
                class="w-14 h-14 bg-securx-cyan/10 rounded-full flex items-center justify-center text-securx-cyan border border-securx-cyan/20 flex-shrink-0 relative z-10">
                <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z">
                    </path>
                </svg>
            </div>
            <div class="relative z-10">
                <h2 class="text-2xl font-extrabold text-white tracking-tight">Comprehensive Medical Record</h2>
                <p class="text-sm text-slate-400 mt-1 max-w-2xl">
                    Maintain your baseline clinical data here. This information powers the SecuRx Intelligence Module to
                    alert pharmacists of potential contraindications.
                </p>
            </div>
        </div>

        <div class="flex overflow-x-auto border-b border-slate-300 pb-px hide-scrollbar">
            <button onclick="switchTab('encounters')" id="tab-encounters"
                class="tab-btn px-6 py-3 text-sm font-bold border-b-2 border-securx-cyan text-securx-cyan whitespace-nowrap transition-colors">
                Clinical Encounters
            </button>
            <button onclick="switchTab('allergies')" id="tab-allergies"
                class="tab-btn px-6 py-3 text-sm font-bold border-b-2 border-transparent text-slate-500 hover:text-slate-800 whitespace-nowrap transition-colors">
                Allergies & Reactions
            </button>
            <button onclick="switchTab('immunizations')" id="tab-immunizations"
                class="tab-btn px-6 py-3 text-sm font-bold border-b-2 border-transparent text-slate-500 hover:text-slate-800 whitespace-nowrap transition-colors">
                Immunizations
            </button>
            <button onclick="switchTab('labs')" id="tab-labs"
                class="tab-btn px-6 py-3 text-sm font-bold border-b-2 border-transparent text-slate-500 hover:text-slate-800 whitespace-nowrap transition-colors">
                Lab Results
            </button>
            <button onclick="switchTab('documents')" id="tab-documents"
                class="tab-btn px-6 py-3 text-sm font-bold border-b-2 border-transparent text-slate-500 hover:text-slate-800 whitespace-nowrap transition-colors">
                Documents
            </button>
        </div>

        <div class="bg-slate-800 border border-slate-700 rounded-2xl p-6 shadow-lg min-h-[500px]">

            <div id="content-encounters" class="tab-content block space-y-4">
                <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-700">
                    <div>
                        <h3 class="text-lg font-bold text-white">Recent Visits</h3>
                        <p class="text-xs text-slate-400">Clinical notes generated by your verified physicians.</p>
                    </div>
                </div>

                <div
                    class="p-5 bg-slate-900/60 border border-slate-700/50 rounded-xl hover:border-slate-600 transition-colors">
                    <div class="flex justify-between items-start mb-3">
                        <div>
                            <p class="font-bold text-securx-cyan text-lg">General Consultation & Diagnostics</p>
                            <p class="text-sm text-slate-400 mt-1 flex items-center gap-2">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                                </svg>
                                Dr. Juan Santos • Angeles Medical Center
                            </p>
                        </div>
                        <div class="text-right">
                            <span
                                class="text-sm text-slate-300 font-mono bg-slate-800 px-3 py-1 rounded-lg border border-slate-700">Oct
                                24, 2026</span>
                        </div>
                    </div>
                    <div class="bg-slate-800/50 p-4 rounded-lg border border-slate-700/50 mt-4">
                        <p class="text-sm text-slate-300 leading-relaxed"><span
                                class="font-bold text-slate-500 mr-2">Assessment:</span> Patient presented with acute
                            bronchitis symptoms, persistent cough for 4 days. Vitals stable. Prescribed Amoxicillin 500mg
                            (TID for 7 days) and advised rest and increased fluid intake. Follow up in 1 week if symptoms
                            persist.</p>
                    </div>
                </div>

                <div
                    class="p-5 bg-slate-900/60 border border-slate-700/50 rounded-xl hover:border-slate-600 transition-colors opacity-80">
                    <div class="flex justify-between items-start mb-3">
                        <div>
                            <p class="font-bold text-securx-cyan text-lg">Annual Physical Examination</p>
                            <p class="text-sm text-slate-400 mt-1 flex items-center gap-2">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                                </svg>
                                Dr. Maria Reyes • AUF Health Clinic
                            </p>
                        </div>
                        <div class="text-right">
                            <span
                                class="text-sm text-slate-300 font-mono bg-slate-800 px-3 py-1 rounded-lg border border-slate-700">Jan
                                12, 2026</span>
                        </div>
                    </div>
                    <div class="bg-slate-800/50 p-4 rounded-lg border border-slate-700/50 mt-4">
                        <p class="text-sm text-slate-300 leading-relaxed"><span
                                class="font-bold text-slate-500 mr-2">Assessment:</span> Routine physical. Patient is in
                            good general health. Blood pressure slightly elevated (130/85). Recommended dietary adjustments
                            (lower sodium) and requested baseline CBC and Lipid Panel.</p>
                    </div>
                </div>
            </div>

            <div id="content-allergies" class="tab-content hidden space-y-4">
                <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-700">
                    <div>
                        <h3 class="text-lg font-bold text-white flex items-center gap-2">
                            <span class="w-2.5 h-2.5 rounded-full bg-red-500 animate-pulse"></span> Known Allergies
                        </h3>
                        <p class="text-xs text-slate-400 mt-1">Logged allergies are cross-referenced with RxNorm during
                            prescribing.</p>
                    </div>
                    <button
                        class="text-xs bg-slate-700 hover:bg-slate-600 border border-slate-500 text-white font-bold py-2 px-4 rounded-lg transition-colors flex items-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm14 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z">
                            </path>
                        </svg>
                        Report New Allergy
                    </button>
                </div>

                <div class="grid grid-cols-1 gap-4">
                    <div
                        class="p-5 bg-red-900/10 border border-red-500/20 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div class="flex items-start gap-4">
                            <div
                                class="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center text-red-400 shrink-0 mt-1">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z">
                                    </path>
                                </svg>
                            </div>
                            <div>
                                <div class="flex items-center gap-3 mb-1">
                                    <p class="font-extrabold text-red-400 text-lg">Penicillin</p>
                                    <span
                                        class="px-2.5 py-0.5 bg-red-500/20 text-red-300 text-[10px] font-bold rounded border border-red-500/20 uppercase tracking-wider">High
                                        Severity</span>
                                </div>
                                <p class="text-sm text-slate-300">Reaction: Severe Hives / Anaphylaxis risk</p>
                            </div>
                        </div>
                        <div class="flex flex-col items-end gap-2">
                            <span
                                class="text-[10px] bg-green-500/10 text-green-400 border border-green-500/20 px-2.5 py-1 rounded font-bold uppercase tracking-wider flex items-center gap-1.5">
                                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                                Clinically Verified
                            </span>
                            <p class="text-xs text-slate-500">By Dr. Santos on Oct 24, 2026</p>
                        </div>
                    </div>

                    <div
                        class="p-5 bg-slate-900/40 border border-slate-700 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div class="flex items-start gap-4">
                            <div
                                class="w-10 h-10 rounded-full bg-orange-500/10 flex items-center justify-center text-orange-400 shrink-0 mt-1">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z">
                                    </path>
                                </svg>
                            </div>
                            <div>
                                <div class="flex items-center gap-3 mb-1">
                                    <p class="font-bold text-white text-lg">Ibuprofen</p>
                                    <span
                                        class="px-2.5 py-0.5 bg-orange-500/20 text-orange-300 text-[10px] font-bold rounded border border-orange-500/20 uppercase tracking-wider">Mild</span>
                                </div>
                                <p class="text-sm text-slate-300">Reaction: Mild stomach upset</p>
                            </div>
                        </div>
                        <div class="flex flex-col items-end gap-2">
                            <span
                                class="text-[10px] bg-securx-gold/10 text-securx-gold border border-securx-gold/20 px-2.5 py-1 rounded font-bold uppercase tracking-wider flex items-center gap-1.5">
                                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                                Pending Doctor Review
                            </span>
                            <p class="text-xs text-slate-500">Reported today</p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="content-immunizations" class="tab-content hidden space-y-4">
                <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-700">
                    <h3 class="text-lg font-bold text-white">Vaccination History</h3>
                    <button
                        class="text-xs bg-slate-700 hover:bg-slate-600 border border-slate-500 text-white font-bold py-2 px-4 rounded-lg transition-colors">
                        + Log Vaccine
                    </button>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div class="p-5 bg-slate-900/60 border border-slate-700/50 rounded-xl relative overflow-hidden">
                        <div
                            class="absolute top-0 right-0 bg-green-500/20 px-3 py-1 rounded-bl-lg border-b border-l border-green-500/20">
                            <span class="text-[10px] font-bold text-green-400 uppercase tracking-wider">Verified</span>
                        </div>
                        <p class="font-bold text-white text-lg mb-2 mt-1">Influenza (Flu Shot)</p>
                        <div class="space-y-1">
                            <p class="text-sm text-slate-300"><span class="text-slate-500 mr-2">Administered:</span> Nov
                                01, 2025</p>
                            <p class="text-sm text-slate-300"><span class="text-slate-500 mr-2">Facility:</span> AUF
                                Medical Center</p>
                        </div>
                    </div>

                    <div
                        class="p-5 bg-slate-900/40 border border-dashed border-slate-600 rounded-xl relative overflow-hidden">
                        <div
                            class="absolute top-0 right-0 bg-securx-gold/10 px-3 py-1 rounded-bl-lg border-b border-l border-securx-gold/20">
                            <span class="text-[10px] font-bold text-securx-gold uppercase tracking-wider">Pending
                                Review</span>
                        </div>
                        <p class="font-bold text-white text-lg mb-2 mt-1">COVID-19 Booster</p>
                        <div class="space-y-1">
                            <p class="text-sm text-slate-300"><span class="text-slate-500 mr-2">Administered:</span> Mar
                                15, 2026</p>
                            <p class="text-sm text-slate-300"><span class="text-slate-500 mr-2">Facility:</span> Pharmacy
                                Walk-in</p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="content-labs" class="tab-content hidden space-y-4">
                <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-700">
                    <h3 class="text-lg font-bold text-white">Laboratory Diagnostics</h3>

                    <div class="flex items-center gap-2">
                        <input type="text" placeholder="Test Name (e.g. Urinalysis)"
                            class="px-3 py-2 text-xs bg-slate-900 border border-slate-600 rounded-lg text-white outline-none focus:border-securx-cyan w-48">
                        <button
                            class="text-xs bg-slate-700 hover:bg-slate-600 border border-slate-500 text-white font-bold py-2 px-4 rounded-lg transition-colors flex items-center gap-2">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"></path>
                            </svg>
                            Upload PDF
                        </button>
                    </div>
                </div>

                <div class="grid grid-cols-1 gap-3">
                    <div
                        class="p-4 bg-slate-900/60 border border-slate-700/50 rounded-xl flex justify-between items-center hover:bg-slate-800 transition-colors cursor-pointer">
                        <div class="flex items-center gap-4">
                            <div
                                class="w-12 h-12 bg-slate-800 border border-slate-600 rounded-xl flex items-center justify-center text-red-400">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z">
                                    </path>
                                </svg>
                            </div>
                            <div>
                                <div class="flex items-center gap-3">
                                    <p class="font-bold text-white text-base">Complete Blood Count (CBC)</p>
                                    <span
                                        class="text-[10px] bg-green-500/10 text-green-400 border border-green-500/20 px-1.5 py-0.5 rounded font-bold uppercase">Verified</span>
                                </div>
                                <p class="text-xs text-slate-400 mt-0.5">Tested on Oct 20, 2025 • AUF Lab</p>
                            </div>
                        </div>
                        <button
                            class="text-securx-cyan text-sm font-bold hover:text-cyan-300 transition-colors bg-securx-cyan/10 px-4 py-2 rounded-lg">View
                            PDF</button>
                    </div>

                    <div
                        class="p-4 bg-slate-900/60 border border-slate-700/50 rounded-xl flex justify-between items-center hover:bg-slate-800 transition-colors cursor-pointer">
                        <div class="flex items-center gap-4">
                            <div
                                class="w-12 h-12 bg-slate-800 border border-slate-600 rounded-xl flex items-center justify-center text-red-400">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z">
                                    </path>
                                </svg>
                            </div>
                            <div>
                                <div class="flex items-center gap-3">
                                    <p class="font-bold text-white text-base">Lipid Panel Results</p>
                                    <span
                                        class="text-[10px] bg-securx-gold/10 text-securx-gold border border-securx-gold/20 px-1.5 py-0.5 rounded font-bold uppercase">Pending
                                        Review</span>
                                </div>
                                <p class="text-xs text-slate-400 mt-0.5">Uploaded Mar 20, 2026 • Patient Added</p>
                            </div>
                        </div>
                        <button
                            class="text-securx-cyan text-sm font-bold hover:text-cyan-300 transition-colors bg-securx-cyan/10 px-4 py-2 rounded-lg">View
                            PDF</button>
                    </div>
                </div>
            </div>

            <div id="content-documents" class="tab-content hidden space-y-4">
                <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-700">
                    <h3 class="text-lg font-bold text-white">Medical Certificates & Files</h3>
                    <button
                        class="text-xs bg-slate-700 hover:bg-slate-600 border border-slate-500 text-white font-bold py-2 px-4 rounded-lg transition-colors flex items-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"></path>
                        </svg>
                        Upload Document
                    </button>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div
                        class="p-4 bg-slate-900/60 border border-slate-700/50 rounded-xl flex items-center justify-between">
                        <div>
                            <div class="flex items-center gap-2">
                                <p class="font-bold text-white">Fit To Work Certificate</p>
                                <span
                                    class="text-[10px] bg-green-500/10 text-green-400 px-1.5 py-0.5 rounded font-bold uppercase border border-green-500/20">Verified</span>
                            </div>
                            <p class="text-xs text-slate-400 mt-1">Issued Jan 2026</p>
                        </div>
                        <button class="text-slate-400 hover:text-white transition-colors"><svg class="w-5 h-5"
                                fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                            </svg></button>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script>
        function switchTab(tabId) {
            document.querySelectorAll('.tab-content').forEach(el => {
                el.classList.remove('block');
                el.classList.add('hidden');
            });

            document.getElementById('content-' + tabId).classList.remove('hidden');
            document.getElementById('content-' + tabId).classList.add('block');

            document.querySelectorAll('.tab-btn').forEach(btn => {
                btn.classList.remove('border-securx-cyan', 'text-securx-cyan');
                btn.classList.add('border-transparent', 'text-slate-500');
            });

            const activeBtn = document.getElementById('tab-' + tabId);
            activeBtn.classList.remove('border-transparent', 'text-slate-500');
            activeBtn.classList.add('border-securx-cyan', 'text-securx-cyan');
        }
    </script>

    <style>
        .hide-scrollbar::-webkit-scrollbar {
            display: none;
        }

        .hide-scrollbar {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }
    </style>
@endsection
