<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Printable SecuRx ID Card</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        /* Print-specific overrides to ensure background colors and formatting stay clean */
        @media print {
            body {
                background-color: white !important;
                margin: 0;
                padding: 0;
            }

            .no-print {
                display: none !important;
            }

            .print-border {
                border: 2px dashed #999 !important;
            }
        }
    </style>
</head>

<body class="bg-gray-100 min-h-screen flex flex-col items-center py-10 text-black font-sans">

    <div
        class="no-print mb-8 p-4 bg-white rounded-lg shadow-md border border-gray-200 w-full max-w-2xl flex justify-between items-center">
        <div>
            <h2 class="font-bold text-gray-800">Print Preview</h2>
            <p class="text-sm text-gray-500">Ensure your printer is set to 100% scale (no margins) for the best result.
            </p>
        </div>
        <button onclick="window.print()"
            class="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-6 rounded-md shadow transition">
            Print ID Card
        </button>
    </div>

    <div class="bg-white w-full max-w-2xl p-10 print-border shadow-xl">

        <div class="flex justify-between items-start border-b-2 border-black pb-6 mb-8">
            <div>
                <a href="{{ route('home') }}" class="flex items-center gap-2 group">
                    <img src="{{ asset('images/logo-1.png') }}" alt="SecuRx Logo"
                        class="h-10 w-auto object-contain transition-transform duration-300 group-hover:scale-105">
                </a>
                <p class="text-sm font-bold uppercase tracking-widest text-gray-600 mt-1">Universal Patient ID</p>
            </div>
            <div class="text-right max-w-xs">
                <p class="text-xs font-bold uppercase">To the Pharmacist:</p>
                <p class="text-xs mt-1">Please scan the QR code below using the SecuRx Portal to securely decrypt the
                    patient's active prescriptions and record DUR telemetry.</p>
            </div>
        </div>

        <div class="flex items-center justify-between px-4">

            <div class="space-y-4">
                <div>
                    <p class="text-xs font-bold text-gray-500 uppercase">Patient Name</p>
                    <p class="text-2xl font-bold">John Doe</p>
                </div>
                <div>
                    <p class="text-xs font-bold text-gray-500 uppercase">Date of Birth</p>
                    <p class="text-lg font-bold">January 15, 2005</p>
                </div>
                <div>
                    <p class="text-xs font-bold text-gray-500 uppercase">Cryptographic UUID</p>
                    <p class="text-lg font-mono font-bold bg-gray-100 px-2 py-1 inline-block border border-gray-300">
                        8F92A-4B7C1-9D2E3</p>
                </div>
            </div>

            <div class="p-2 border-4 border-black">
                <img src="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=SecuRx:8F92A-4B7C1-9D2E3&color=000000"
                    alt="Patient QR Code" class="w-48 h-48">
            </div>

        </div>

        <div class="mt-12 pt-6 border-t border-gray-300 text-center">
            <p class="text-xs font-bold">DO NOT SHARE THIS CODE ONLINE OR VIA SOCIAL MEDIA.</p>
            <p class="text-xs text-gray-500 mt-1">This document serves as your offline medical key. Store it securely in
                your wallet or with your medical records.</p>
            <p class="text-[10px] text-gray-400 mt-6 uppercase tracking-widest">Generated by SecuRx on
                {{ date('M d, Y') }} at {{ date('H:i') }}</p>
        </div>

    </div>

</body>

</html>
