@extends('layouts.public')

@section('title', 'Terms of Service')

@section('content')
<div class="flex flex-col items-center max-w-4xl mx-auto w-full">
    
    <div class="text-center mb-12 mt-8">
        <div class="inline-block py-1.5 px-4 rounded-full bg-securx-cyan/10 border border-securx-cyan/20 text-securx-cyan text-xs font-bold tracking-widest uppercase mb-4">
            Legal Agreement
        </div>
        <h1 class="text-4xl font-extrabold text-securx-navy mb-4 tracking-tight">
            Terms of Service
        </h1>
        <p class="text-sm text-gray-500 font-medium">
            Last Updated: {{ date('F d, Y') }}
        </p>
    </div>

    <div class="glass-panel bg-white/90 p-8 md:p-12 w-full text-gray-700 leading-relaxed space-y-8 text-sm md:text-base">
        
        <section>
            <h2 class="text-xl font-bold text-securx-navy mb-3">1. Acceptance of Terms</h2>
            <p>
                By accessing and utilizing the SecuRx network, including the generation, storage, or scanning of cryptographic prescription QR codes, you agree to be bound by these Terms of Service. If you do not agree to these terms, you must abstain from using the platform.
            </p>
        </section>

        <section>
            <h2 class="text-xl font-bold text-securx-navy mb-3">2. Platform Role & Medical Liability</h2>
            <p>
                SecuRx is exclusively a technology provider offering cryptographic data routing and Drug Utilization Review (DUR) telemetry. <strong>SecuRx does not provide medical advice, diagnosis, or treatment.</strong> The responsibility for the accuracy of a prescription, dosage amounts, and clinical judgment rests entirely with the verified prescribing physician. Pharmacists retain their professional autonomy and legal obligation to verify patient identity before dispensing.
            </p>
        </section>

        <section>
            <h2 class="text-xl font-bold text-securx-navy mb-3">3. User Responsibilities</h2>
            <ul class="list-none space-y-4 text-gray-600">
                <li class="flex gap-3">
                    <span class="text-securx-cyan font-bold">A.</span> 
                    <span><strong>Physicians:</strong> Must maintain an active PRC license and ensure their SecuRx account credentials (including 2FA tokens) are never shared.</span>
                </li>
                <li class="flex gap-3">
                    <span class="text-securx-cyan font-bold">B.</span> 
                    <span><strong>Pharmacists:</strong> Must accurately log dispensing quantities into the network to maintain the integrity of the DUR engine and prevent patient harm.</span>
                </li>
                <li class="flex gap-3">
                    <span class="text-securx-cyan font-bold">C.</span> 
                    <span><strong>Patients:</strong> Are responsible for the physical and digital safekeeping of their generated QR codes. SecuRx is not liable for unauthorized dispensing resulting from a patient sharing their active QR code.</span>
                </li>
            </ul>
        </section>

        <section>
            <h2 class="text-xl font-bold text-securx-navy mb-3">4. System Integrity & Forgery</h2>
            <p>
                Any attempt to reverse-engineer, duplicate, or alter the dynamic UUIDs or cryptographic signatures generated by SecuRx is strictly prohibited and will result in immediate permanent account suspension and potential reporting to local law enforcement and health authorities.
            </p>
        </section>

        <hr class="border-gray-200">

        <section class="text-center text-gray-500 text-sm">
            <p>For legal inquiries, please contact our administrative team at <a href="mailto:legal@securx.test" class="text-securx-cyan hover:underline">legal@securx.test</a>.</p>
        </section>

    </div>
</div>
@endsection